apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: split-traffic
spec:
  service: api-dummy-service
  backends:
  - service: grpc-service
    weight: 50
  - service: redis-service
    weight: 50
