apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: split-traffic
spec:
  service: api-dummy-service
  backends:
  - service: clientqueuerabbit
    weight: 50
  - service: faultytraffic4
    weight: 50
